/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured Providers */
        get: operations["configured_providers_v1_auth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description 갱신 토큰으로 새 토큰 쌍. 갱신 토큰은 한 번 쓰면 새것으로 바뀐다.
         */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 이 기기의 갱신 토큰을 무효화. 액세스 토큰은 수명(기본 1시간)이 끝나면 자동으로 만료
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 서비스 토큰을 검증하고 우리 토큰을 발급. 처음이면 계정을 만든다.
         */
        post: operations["login_v1_auth__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identities */
        get: operations["identities_v1_me_identities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/identities/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Identity
         * @description 로그인된 계정에 다른 로그인 수단을 추가
         */
        post: operations["link_identity_v1_me_identities__provider__post"];
        /** Unlink Identity */
        delete: operations["unlink_identity_v1_me_identities__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_v1_me_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instagram */
        get: operations["instagram_v1_me_instagram_get"];
        put?: never;
        post?: never;
        /** Disconnect Instagram */
        delete: operations["disconnect_instagram_v1_me_instagram_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/instagram/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Instagram */
        post: operations["authorize_instagram_v1_me_instagram_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social/instagram/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instagram Callback */
        get: operations["instagram_callback_v1_social_instagram_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing */
        get: operations["get_billing_v1_me_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/billing/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Billing */
        post: operations["sync_billing_v1_me_billing_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Feedback */
        get: operations["my_feedback_v1_me_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Feedback */
        delete: operations["delete_feedback_v1_me_feedback__feedback_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Queue */
        get: operations["feedback_queue_v1_admin_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Feedback */
        patch: operations["review_feedback_v1_admin_feedback__feedback_id__patch"];
        trace?: never;
    };
    "/v1/admin/feedback/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Feedback */
        post: operations["analyze_feedback_v1_admin_feedback_triage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/triages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Triages */
        get: operations["list_triages_v1_admin_triages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/triages/{triage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide Triage */
        patch: operations["decide_triage_v1_admin_triages__triage_id__patch"];
        trace?: never;
    };
    "/v1/admin/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns */
        get: operations["campaigns_v1_admin_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_v1_admin_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve Campaign */
        patch: operations["approve_campaign_v1_admin_campaigns__campaign_id__patch"];
        trace?: never;
    };
    "/v1/sponsorships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sponsorships */
        get: operations["sponsorships_v1_sponsorships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sponsorships/{campaign_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Event */
        post: operations["record_event_v1_sponsorships__campaign_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_v1_me_profile_get"];
        /** Put Profile */
        put: operations["put_profile_v1_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Consent */
        post: operations["grant_consent_v1_me_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/consents/{consent_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Consent */
        delete: operations["revoke_consent_v1_me_consents__consent_type__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saju": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Saju */
        put: operations["put_saju_v1_me_saju_put"];
        post?: never;
        /** Delete Saju */
        delete: operations["delete_saju_v1_me_saju_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/type-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type Card */
        get: operations["get_type_card_v1_me_type_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description 탈퇴: 계정 행은 '탈퇴' 표시로 남겨 같은 토큰을 막고, 개인정보는 모두 삭제.
         *     본인이 올린 사진(얼굴이 있을 수 있음)은 파일까지 지우고 영향받은 장면은 재집계.
         */
        delete: operations["delete_account_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookmarks */
        get: operations["bookmarks_v1_me_bookmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/bookmarks/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Bookmark */
        put: operations["save_bookmark_v1_me_bookmarks__place_id__put"];
        post?: never;
        /** Remove Bookmark */
        delete: operations["remove_bookmark_v1_me_bookmarks__place_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend */
        get: operations["recommend_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/places/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place Detail */
        get: operations["place_detail_v1_places__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{rec_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_v1_recommendations__rec_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Photo */
        post: operations["upload_photo_v1_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diagnosis/{kind}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnosis Questions */
        get: operations["diagnosis_questions_v1_diagnosis__kind__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/diagnosis/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnosis */
        post: operations["diagnosis_v1_diagnosis__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description 자동 태깅 신뢰도가 낮은 장면 + 최근 90일 사용자 태그 수정 제보가 3건 이상인 장면.
         */
        get: operations["review_queue_v1_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Scene */
        patch: operations["edit_scene_v1_admin_scenes__scene_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppleDeletionProof */
        AppleDeletionProof: {
            /** Identity Token */
            identity_token: string;
            /** Authorization Code */
            authorization_code: string;
            /** Nonce */
            nonce: string;
        };
        /** BillingStatus */
        BillingStatus: {
            /** User Id */
            user_id: string;
            /** Premium */
            premium: boolean;
            /** Premium Until */
            premium_until?: string | null;
            /** Management Url */
            management_url?: string | null;
            /** Configured */
            configured: boolean;
        };
        /** Body_upload_photo_v1_photos_post */
        Body_upload_photo_v1_photos_post: {
            /**
             * Spot Id
             * Format: uuid
             */
            spot_id: string;
            /** File */
            file: string;
        };
        /** Bookmark */
        Bookmark: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            cover_photo?: components["schemas"]["Photo"] | null;
        };
        /** CampaignApproval */
        CampaignApproval: {
            /** Approved */
            approved: boolean;
        };
        /** CampaignEvent */
        CampaignEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "impression" | "click";
        };
        /** CampaignIn */
        CampaignIn: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
            /** Sponsor */
            sponsor: string;
            /** Headline */
            headline: string;
            /**
             * Placement
             * @enum {string}
             */
            placement: "banner" | "priority";
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
        };
        /** ConsentIn */
        ConsentIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "style_profile" | "saju" | "photo_analysis" | "location";
        };
        /** DailyContext */
        DailyContext: {
            /** Pillar */
            pillar: string;
            /**
             * Day Element
             * @enum {string}
             */
            day_element: "wood" | "fire" | "earth" | "metal" | "water";
            /** Day Label */
            day_label: string;
            /**
             * Personal Element
             * @enum {string}
             */
            personal_element: "wood" | "fire" | "earth" | "metal" | "water";
            /** Personal Label */
            personal_label: string;
            /** Deficient Elements */
            deficient_elements: ("wood" | "fire" | "earth" | "metal" | "water")[];
            /** Deficient Labels */
            deficient_labels: string[];
            /** Minimum Percent */
            minimum_percent: number;
            /** Target Elements */
            target_elements?: ("wood" | "fire" | "earth" | "metal" | "water")[];
            /** Target Labels */
            target_labels?: string[];
            /** Element Priorities */
            element_priorities?: components["schemas"]["ElementPriority"][];
            /**
             * Method
             * @default personal70_daily30_v1
             */
            method: string;
            /** Note */
            note: string;
        };
        /** DataSource */
        DataSource: {
            /** Provider */
            provider: string;
            /** Label */
            label: string;
            /** License Url */
            license_url: string;
            /** Fetched At */
            fetched_at?: string | null;
            /** Count */
            count?: number | null;
            /** Regions */
            regions?: string[];
            /** Url */
            url?: string | null;
            /** Group Counts */
            group_counts?: {
                [key: string]: number;
            };
        };
        /** DeleteAccountIn */
        DeleteAccountIn: {
            apple?: components["schemas"]["AppleDeletionProof"] | null;
        };
        /** DiagnosisIn */
        DiagnosisIn: {
            /**
             * Answers
             * @description 각 질문에서 고른 선택지 번호(0부터)
             */
            answers: number[];
        };
        /** DiagnosisOut */
        DiagnosisOut: {
            /** Result */
            result: string;
            /** Result Label */
            result_label: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Second */
            second?: string | null;
            /** Second Label */
            second_label?: string | null;
            /** Note */
            note: string;
        };
        /** DiagnosisQuestion */
        DiagnosisQuestion: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Options */
            options: string[];
        };
        /** DiningCuration */
        DiningCuration: {
            /** Note */
            note: string;
            /** Sources */
            sources: components["schemas"]["VisitorSource"][];
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
        };
        /** DiscoveryEvidence */
        DiscoveryEvidence: {
            /** Photo Count */
            photo_count: number;
            /** Popularity */
            popularity?: components["schemas"]["PopularitySignal"][];
            curation?: components["schemas"]["DiningCuration"] | null;
        };
        /** ElementPriority */
        ElementPriority: {
            /**
             * Element
             * @enum {string}
             */
            element: "wood" | "fire" | "earth" | "metal" | "water";
            /** Label */
            label: string;
            /** Personal Percent */
            personal_percent: number;
            /** Personal Points */
            personal_points: number;
            /** Day Points */
            day_points: number;
            /**
             * Day Relation
             * @enum {string}
             */
            day_relation: "day_generates_place" | "same" | "place_generates_day" | "place_controls_day" | "day_controls_place";
            /** Day Relation Label */
            day_relation_label: string;
            /**
             * Score
             * @description 개인 부족 정도와 일진 관계의 합계. 사진 정합도가 아님
             */
            score: number;
            /** Is Candidate */
            is_candidate: boolean;
        };
        /** ElementSource */
        ElementSource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Visited */
            visited?: boolean | null;
            /** Rating */
            rating?: number | null;
            /** Photo Id */
            photo_id?: string | null;
            /**
             * Tag Corrections
             * @description 실제와 달랐던 태그. 예: {"lighting": "warm_artificial"}
             */
            tag_corrections?: {
                [key: string]: string;
            } | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /**
             * Category
             * @enum {string}
             */
            category: "bug" | "idea" | "place" | "other";
            /** Message */
            message: string;
            /**
             * Ai Consent
             * @default false
             */
            ai_consent: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed Text */
            reviewed_text?: string | null;
        };
        /** FeedbackReview */
        FeedbackReview: {
            /** Reviewed Text */
            reviewed_text: string;
        };
        /** FeedbackSubmission */
        FeedbackSubmission: {
            /**
             * Category
             * @enum {string}
             */
            category: "bug" | "idea" | "place" | "other";
            /** Message */
            message: string;
            /**
             * Ai Consent
             * @default false
             */
            ai_consent: boolean;
        };
        /** GrowthSession */
        GrowthSession: {
            /** User Id */
            user_id: string;
            /** Is Admin */
            is_admin: boolean;
            /** Instagram Configured */
            instagram_configured: boolean;
            /** Billing Configured */
            billing_configured: boolean;
            /** Ai Configured */
            ai_configured: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityOut */
        IdentityOut: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "google" | "apple" | "naver" | "kakao";
            /** Email */
            email: string | null;
            /** Display Name */
            display_name: string | null;
            /** Last Login At */
            last_login_at: string;
        };
        /** InstagramPost */
        InstagramPost: {
            /** Permalink */
            permalink: string;
            /** Label */
            label: string;
            /** Checked At */
            checked_at: string;
        };
        /** Links */
        Links: {
            /** Naver Map Url */
            naver_map_url?: string | null;
            /**
             * Google Place Id
             * @description 영업시간 등은 앱이 Places API로 실시간 조회 (서버는 저장 안 함)
             */
            google_place_id?: string | null;
            /** Kakao Place Id */
            kakao_place_id?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Token
             * @description 구글·애플: ID 토큰(JWT). 네이버·카카오: 액세스 토큰
             */
            token: string;
            /**
             * Nonce
             * @description 구글·애플: 요청 때 쓴 nonce (재생 공격 방지, 선택)
             */
            nonce?: string | null;
            /**
             * Name
             * @description 애플: 첫 로그인 때만 앱이 받는 이름
             */
            name?: string | null;
            /**
             * Authorization Code
             * @description Apple 승인 코드: 서버에서 교환 후 암호화 보관
             */
            authorization_code?: string | null;
        };
        /** MetricSource */
        MetricSource: {
            /** Url */
            url: string;
            /** Label */
            label: string;
            /** Excerpt */
            excerpt?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Checked At */
            checked_at?: string | null;
        };
        /** Photo */
        Photo: {
            /** Url */
            url: string;
            /** Attribution */
            attribution: string;
            /** License */
            license: string;
            /**
             * Keep Aspect Ratio
             * @description 공공누리 3유형(변경 금지)은 자르지 말고 원본 비율로
             */
            keep_aspect_ratio: boolean;
            /** Source Url */
            source_url?: string | null;
            /** License Url */
            license_url?: string | null;
            /** Original Url */
            original_url?: string | null;
            /** Title */
            title?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** PhotoAccepted */
        PhotoAccepted: {
            /** Photo Id */
            photo_id: string;
            /** Job Queued */
            job_queued: boolean;
            /** Taken At */
            taken_at: string | null;
        };
        /** PillarOut */
        PillarOut: {
            /** Hanja */
            hanja: string;
            /** Hangul */
            hangul: string;
        };
        /** PlaceDetail */
        PlaceDetail: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Place Group
             * @default all
             * @enum {string}
             */
            place_group: "all" | "cafe" | "travel" | "festival";
            /** Address */
            address: string | null;
            best_scene: components["schemas"]["SceneScore"] | null;
            /** Other Scenes */
            other_scenes: components["schemas"]["SceneScore"][];
            /** Tips */
            tips: components["schemas"]["Tip"][];
            /** Visit Notes */
            visit_notes: string[];
            /** Open On Visit Date */
            open_on_visit_date: boolean | null;
            /** Photos */
            photos: components["schemas"]["Photo"][];
            /**
             * Instagram Posts
             * @description 지점 확인을 마친 공개 게시물. 원본 임베드 표시용이며 사진 분석 점수에 포함하지 않음
             */
            instagram_posts?: components["schemas"]["InstagramPost"][];
            links: components["schemas"]["Links"];
            /**
             * Analysis Pending
             * @description 아직 입력과 근거가 갖춰진 평가 항목이 없는 장소
             * @default false
             */
            analysis_pending: boolean;
            /**
             * Match Basis
             * @default photo
             * @enum {string}
             */
            match_basis: "photo" | "category" | "nearby";
            source?: components["schemas"]["DataSource"] | null;
            /** Discovery Reasons */
            discovery_reasons?: components["schemas"]["Reason"][];
            /** Opening Hours */
            opening_hours?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Recommended Elements */
            recommended_elements?: ("wood" | "fire" | "earth" | "metal" | "water")[];
            saju_match?: components["schemas"]["ElementPriority"] | null;
            scoring?: components["schemas"]["ScoreExplanation"] | null;
            /** Score Weights */
            score_weights?: components["schemas"]["ScoreWeight"][];
            element_profile?: components["schemas"]["PlaceElementProfile"] | null;
            discovery?: components["schemas"]["DiscoveryEvidence"] | null;
            hours?: components["schemas"]["PlaceHours"] | null;
        };
        /** PlaceElementProfile */
        PlaceElementProfile: {
            /** Elements */
            elements: ("wood" | "fire" | "earth" | "metal" | "water")[];
            /**
             * Basis
             * @enum {string}
             */
            basis: "traditional" | "regional" | "landscape" | "unassigned";
            /** Label */
            label: string;
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["ElementSource"][];
            /** Checked At */
            checked_at: string;
        };
        /** PlaceHours */
        PlaceHours: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "naver" | "official" | "openstreetmap";
            /**
             * Schedule Kind
             * @default regular
             * @enum {string}
             */
            schedule_kind: "regular" | "dated" | "source_text";
            /** Source Label */
            source_label: string;
            /** Source Url */
            source_url: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Stale */
            stale: boolean;
            /** Summary */
            summary: string;
            /** Weekly Hours */
            weekly_hours: string[];
            /** Notes */
            notes: string[];
            /** Address */
            address: string;
            /** Branch Name */
            branch_name: string;
        };
        /** PopularitySignal */
        PopularitySignal: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "naver_reviews" | "instagram_place_posts" | "naver_local_rank";
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Source Url */
            source_url: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Scope */
            scope: string;
        };
        /**
         * Problem
         * @description 오류 응답 (RFC 9457 형식).
         */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
        };
        /** Profile */
        Profile: {
            /**
             * Gender
             * @default undisclosed
             * @enum {string}
             */
            gender: "female" | "male" | "other" | "undisclosed";
            /** Birth Year */
            birth_year?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Pc Season */
            pc_season?: ("spring_warm" | "summer_cool" | "autumn_warm" | "winter_cool") | null;
            /** Pc Subtone */
            pc_subtone?: ("light" | "bright" | "true" | "mute" | "deep") | null;
            /** Body Type */
            body_type?: ("straight" | "wave" | "natural") | null;
            /** Mbti */
            mbti?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Gender
             * @default undisclosed
             * @enum {string}
             */
            gender: "female" | "male" | "other" | "undisclosed";
            /** Birth Year */
            birth_year?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Pc Season */
            pc_season?: ("spring_warm" | "summer_cool" | "autumn_warm" | "winter_cool") | null;
            /** Pc Subtone */
            pc_subtone?: ("light" | "bright" | "true" | "mute" | "deep") | null;
            /** Body Type */
            body_type?: ("straight" | "wave" | "natural") | null;
            /** Mbti */
            mbti?: string | null;
            /**
             * Profile Exists
             * @default false
             */
            profile_exists: boolean;
            /** Height Band */
            height_band?: ("small" | "medium" | "tall") | null;
            /**
             * Saju Enabled
             * @default false
             */
            saju_enabled: boolean;
            /** Saju Element */
            saju_element?: ("wood" | "fire" | "earth" | "metal" | "water") | null;
            /** Saju Percents */
            saju_percents?: {
                [key: string]: number;
            } | null;
        };
        /** Reason */
        Reason: {
            /** Label */
            label: string;
            /** Points */
            points: number;
            /**
             * Layer
             * @enum {string}
             */
            layer: "practical" | "auxiliary";
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Recommendation Id */
            recommendation_id: number;
            /** Place Id */
            place_id: string;
            /** Place Name */
            place_name: string;
            /**
             * Place Group
             * @default all
             * @enum {string}
             */
            place_group: "all" | "cafe" | "travel" | "festival";
            /** Spot Name */
            spot_name: string;
            /** Spot Id */
            spot_id: string;
            /** Scene Id */
            scene_id: string;
            /**
             * Time Slot
             * @enum {string}
             */
            time_slot: "morning" | "midday" | "golden_hour" | "night";
            /** Time Slot Label */
            time_slot_label: string;
            /** Score */
            score: number;
            /** Practical Score */
            practical_score: number | null;
            /** Distance M */
            distance_m: number;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            cover_photo?: components["schemas"]["Photo"] | null;
            /**
             * Instagram Post Count
             * @description 연결된 공개 Instagram 게시물 수. 사진 분석·정합도와 별개
             * @default 0
             */
            instagram_post_count: number;
            links: components["schemas"]["Links"];
            /**
             * Match Basis
             * @default photo
             * @enum {string}
             */
            match_basis: "photo" | "category" | "nearby";
            source?: components["schemas"]["DataSource"] | null;
            /**
             * Fit Score
             * @description 입력 프로필과 확인된 사진 특징의 정합도. 평가 근거 또는 입력이 없으면 null
             */
            fit_score?: number | null;
            /**
             * Recommended Elements
             * @description 이 장소에서 실제 대응하는 보완 오행·일진 오행
             */
            recommended_elements?: ("wood" | "fire" | "earth" | "metal" | "water")[];
            saju_match?: components["schemas"]["ElementPriority"] | null;
            scoring?: components["schemas"]["ScoreExplanation"] | null;
            element_profile?: components["schemas"]["PlaceElementProfile"] | null;
            discovery?: components["schemas"]["DiscoveryEvidence"] | null;
            hours?: components["schemas"]["PlaceHours"] | null;
        };
        /** RecommendationList */
        RecommendationList: {
            /**
             * Visit Date
             * Format: date
             */
            visit_date: string;
            /** Radius M */
            radius_m: number;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /**
             * Missing Inputs
             * @description 입력하면 추천이 더 정확해지는 항목
             */
            missing_inputs: string[];
            daily?: components["schemas"]["DailyContext"] | null;
            catalog?: components["schemas"]["DataSource"] | null;
            /**
             * Place Group
             * @default all
             * @enum {string}
             */
            place_group: "all" | "cafe" | "travel" | "festival";
            /** Score Weights */
            score_weights?: components["schemas"]["ScoreWeight"][];
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Scene Id */
            scene_id: string;
            /** Place Name */
            place_name: string;
            /** Spot Name */
            spot_name: string;
            /** Time Slot */
            time_slot: string;
            /** Season */
            season: string;
            /** Confidence */
            confidence: number | null;
            /** Photo Count */
            photo_count: number | null;
            /** Reasons */
            reasons: string[];
        };
        /** SajuIn */
        SajuIn: {
            /**
             * Birth Date
             * @description 선택한 달력의 YYYY-MM-DD. 음력 2월 30일도 지원
             */
            birth_date: string;
            /**
             * Birth Time
             * @description 모르면 비워두면 년·월·일 6글자로 계산
             */
            birth_time?: string | null;
            /**
             * Birth Hour Branch
             * @description 자·축·인·묘·진·사·오·미·신·유·술·해. 직접 시지 선택, birth_time과 동시 입력 불가
             */
            birth_hour_branch?: ("zi" | "chou" | "yin" | "mao" | "chen" | "si" | "wu" | "wei" | "shen" | "you" | "xu" | "hai") | null;
            /**
             * Calendar
             * @default solar
             * @enum {string}
             */
            calendar: "solar" | "lunar";
            /**
             * Leap Month
             * @description 음력 윤달 출생이면 true
             * @default false
             */
            leap_month: boolean;
            /**
             * Consent
             * @description true여야 계산. 원본은 계산 직후 폐기되고 저장되지 않음
             */
            consent: boolean;
        };
        /** SajuOut */
        SajuOut: {
            /**
             * Method
             * @description forceteller_v1: 궁성·조후 보정(포스텔러 방식) + 합충 보정
             */
            method: string;
            /**
             * Percents
             * @description 오행 비율(%)
             */
            percents: {
                [key: string]: number;
            };
            /**
             * Dominant Element
             * @description 가장 많은 오행 — 추천에 쓰는 값
             * @enum {string}
             */
            dominant_element: "wood" | "fire" | "earth" | "metal" | "water";
            /** Dominant Label */
            dominant_label: string;
            /**
             * Pillars
             * @description 년·월·일·(시)주. 표시용이며 저장하지 않음
             */
            pillars: {
                [key: string]: components["schemas"]["PillarOut"];
            };
            /**
             * Corrections
             * @description 적용된 합충·조후 보정 내역
             */
            corrections: string[];
            /** Has Birth Time */
            has_birth_time: boolean;
        };
        /** SceneEdit */
        SceneEdit: {
            /** Color Temp */
            color_temp?: ("warm" | "neutral" | "cool") | null;
            /** Brightness */
            brightness?: ("bright_soft" | "mid" | "high_contrast") | null;
            /** Saturation */
            saturation?: ("muted" | "mid" | "vivid") | null;
            /** Lighting */
            lighting?: ("diffused_natural" | "direct_golden" | "warm_artificial" | "cool_artificial_night") | null;
            /** Form */
            form?: ("linear" | "curved" | "organic") | null;
            /** Texture */
            texture?: ("sleek" | "soft" | "rough") | null;
            /** Scale */
            scale?: ("compact" | "medium" | "spacious") | null;
            /** Crowd Level */
            crowd_level?: ("quiet" | "moderate" | "busy") | null;
            /** Place Character */
            place_character?: ("detail" | "concept") | null;
            /** Photo Mood */
            photo_mood?: ("structural" | "emotional") | null;
            /** Elements */
            elements?: ("wood" | "fire" | "earth" | "metal" | "water")[] | null;
            /**
             * Verify
             * @description true면 검수 완료로 확정 (이후 자동 태깅이 덮어쓰지 않음)
             * @default true
             */
            verify: boolean;
        };
        /** SceneScore */
        SceneScore: {
            /** Scene Id */
            scene_id: string;
            /** Spot Id */
            spot_id: string;
            /** Spot Name */
            spot_name: string;
            /**
             * Time Slot
             * @enum {string}
             */
            time_slot: "morning" | "midday" | "golden_hour" | "night";
            /** Season */
            season: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /**
             * Evidence
             * @description 점수의 근거: 사진 분석 또는 사람 확정 (분류 추정은 채점되지 않음)
             * @enum {string}
             */
            evidence: "photos" | "human";
            /** Photo Count */
            photo_count?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Recommended Elements */
            recommended_elements?: ("wood" | "fire" | "earth" | "metal" | "water")[];
            scoring?: components["schemas"]["ScoreExplanation"] | null;
        };
        /** ScoreExplanation */
        ScoreExplanation: {
            /**
             * Basis
             * @enum {string}
             */
            basis: "category" | "photo";
            /** Score */
            score: number | null;
            /** Note */
            note: string;
            /** Metrics */
            metrics: components["schemas"]["ScoreMetric"][];
            /** Evaluated Weight */
            evaluated_weight?: number | null;
            /** Total Weight */
            total_weight?: number | null;
            /** Evidence Url */
            evidence_url?: string | null;
            /** Evidence Method */
            evidence_method?: string | null;
            visitor_context?: components["schemas"]["VisitorContext"] | null;
        };
        /** ScoreMetric */
        ScoreMetric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Points */
            points: number | null;
            /** Maximum */
            maximum: number | null;
            /** Weight */
            weight: number;
            /**
             * Status
             * @enum {string}
             */
            status: "scored" | "missing_input" | "pending" | "optional";
            /**
             * Note
             * @default
             */
            note: string;
            /** Sources */
            sources?: components["schemas"]["MetricSource"][];
        };
        /** ScoreWeight */
        ScoreWeight: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Detail */
            detail: string;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
        };
        /** Tip */
        Tip: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "outfit" | "composition" | "light";
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description 액세스 토큰 수명(초)
             */
            expires_in: number;
            /** User Id */
            user_id: string;
            /**
             * Is New
             * @description 이번 로그인으로 계정이 새로 만들어졌는지
             */
            is_new: boolean;
            /**
             * Profile Exists
             * @description false면 온보딩 화면으로
             */
            profile_exists: boolean;
        };
        /** TriageBatch */
        TriageBatch: {
            /** Feedback Ids */
            feedback_ids: string[];
        };
        /** TriageDecision */
        TriageDecision: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "planned" | "done" | "dismissed";
            /** Note */
            note: string;
        };
        /** TypeCard */
        TypeCard: {
            /** Name */
            name: string;
            /** Subtitle */
            subtitle: string;
            /** Best Light */
            best_light: string[];
            /** Good Backgrounds */
            good_backgrounds: string[];
            /** Avoid */
            avoid: string[];
            /** Lucky */
            lucky?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitorContext */
        VisitorContext: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** As Of */
            as_of: string;
            /** Catalog Count */
            catalog_count: number;
            /** Measured Count */
            measured_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ranked" | "unavailable" | "insufficient";
            /** Rank */
            rank?: number | null;
            /** Visitors */
            visitors?: number | null;
            /** Percentile */
            percentile?: number | null;
            /** Unit Label */
            unit_label?: string | null;
            /** Sources */
            sources?: components["schemas"]["VisitorSource"][];
        };
        /** VisitorSource */
        VisitorSource: {
            /** Url */
            url: string;
            /** Label */
            label: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    configured_providers_v1_auth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "apple" | "naver" | "kakao";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    identities_v1_me_identities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityOut"][];
                };
            };
        };
    };
    link_identity_v1_me_identities__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "apple" | "naver" | "kakao";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_identity_v1_me_identities__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "apple" | "naver" | "kakao";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteAccountIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_v1_me_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthSession"];
                };
            };
        };
    };
    instagram_v1_me_instagram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    disconnect_instagram_v1_me_instagram_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorize_instagram_v1_me_instagram_authorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    instagram_callback_v1_social_instagram_callback_get: {
        parameters: {
            query: {
                state: string;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_billing_v1_me_billing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingStatus"];
                };
            };
        };
    };
    sync_billing_v1_me_billing_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingStatus"];
                };
            };
        };
    };
    submit_feedback_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_feedback_v1_me_feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
        };
    };
    delete_feedback_v1_me_feedback__feedback_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_queue_v1_admin_feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
        };
    };
    review_feedback_v1_admin_feedback__feedback_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_feedback_v1_admin_feedback_triage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_triages_v1_admin_triages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    decide_triage_v1_admin_triages__triage_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                triage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaigns_v1_admin_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_campaign_v1_admin_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_campaign_v1_admin_campaigns__campaign_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignApproval"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sponsorships_v1_sponsorships_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_m?: number;
                place_group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_event_v1_sponsorships__campaign_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_consent_v1_me_consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_v1_me_consents__consent_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_type: "style_profile" | "saju" | "photo_analysis" | "location";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_saju_v1_me_saju_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SajuIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SajuOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_saju_v1_me_saju_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_type_card_v1_me_type_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeCard"];
                };
            };
        };
    };
    delete_account_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteAccountIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bookmarks_v1_me_bookmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
        };
    };
    save_bookmark_v1_me_bookmarks__place_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_bookmark_v1_me_bookmarks__place_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_v1_recommendations_get: {
        parameters: {
            query: {
                /** @description 대한민국 범위 */
                lat: number;
                lng: number;
                date?: string | null;
                radius_m?: number;
                time_slot?: ("morning" | "midday" | "golden_hour" | "night") | null;
                use_saju?: boolean;
                place_group?: "all" | "cafe" | "travel" | "festival";
                limit?: number;
                photo_only?: boolean;
                min_fit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_detail_v1_places__place_id__get: {
        parameters: {
            query?: {
                date?: string | null;
                use_saju?: boolean;
            };
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_v1_recommendations__rec_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    upload_photo_v1_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_v1_photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoAccepted"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnosis_questions_v1_diagnosis__kind__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "personal-color" | "body-type";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisQuestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnosis_v1_diagnosis__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "personal-color" | "body-type";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosisIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_v1_admin_review_queue_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_scene_v1_admin_scenes__scene_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
